# Generated by Django 6.0.6 on 2026-07-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_ip', models.GenericIPAddressField()),
                ('device_type', models.CharField(max_length=100)),
            ],
        ),
    ]
